### PR TITLE
Use .NET standard libraries and IBM00858 encoding for text

### PR DESCRIPTION
**Pull request by Xenoage**
See changes discussed in https://github.com/lukevp/ESC-POS-.NET/issues/26

### CODE REVIEW

**Comment by kodejack** [comment]
I tried this on iOS and replacing SerialPortStream with System.IO.Ports does not work. As it is not compatible.

**Comment by Xenoage** [comment]
I guess, it is only working for Windows, Linux and MacOSX. See https://github.com/dotnet/corefx/tree/master/src/System.IO.Ports/src/System/IO/Ports , `SerialPort.*.cs`

**Comment by lukevp** [comment]
@kodejack  are you currently using the production version with SerialPortStream on iOS?  Or is the limitation of System.IO.Ports the same as SerialPortStream (Windows, Linux, OSX)?

**Comment by kodejack** [comment]
Sorry to clarify, it works fine on iOS, Android and UWP with SerialPortStream v2.2.0.

**Comment by Xenoage** [comment]
OK, then it's bad for you to switch the library... Maybe the two implementations can coexist in the same project?

**Comment by YZahringer** [comment]
`SerialPortStream` does not support UWP, iOS or Android. The library is compatible with Win32 and Linux applications. See https://github.com/jcurl/SerialPortStream/issues/94.

I also use `System.IO.Ports`, I was waiting for the .NET Core 3.0 version to do the PR: https://github.com/lukevp/ESC-POS-.NET/issues/17

In my opinion, the encoding should be configurable. A public Encoding property with `UTF8` or `Unicode` by default would be better. This would avoid the use of an additional dependency `System.Text.Encoding.CodePages`.

Why not use `BinaryWriter` and `BinaryReader` for the implementation of `SerialPrinter`?

**Comment by lukevp** [comment]
@YZahringer,  @kodejack  I will defer to you two on this topic as I haven't tested the library on UWP, iOS or Android.  @kodejack  have you actually tested on UWP?  Or is this the situation we are in:

System.IO.Ports (in .net core 3.0) works on these platforms:
Windows, Linux, UWP, (OSX?)
but not on these platforms (is this through Xamarin?):
iOS, Android

SerialPortStream works on these platforms:
**Desktop**: Windows, Linux, (OSX?)
**Mobile**: iOS, Android
but not on these platforms (is this through Xamarin?):
**Desktop**: UWP

And this is because UWP is sandboxed away from Win32, but System.IO.Ports has native support in .net core 3.0 so under UWP it is able to communicate to the libraries?

Is there any way that System.IO.Ports will eventually work on mobile platforms?

My thinking is that unless there is compatibility across all platforms with one or the other dependency, we should be able to swap out the underlying serial port library dependency based on our needs.  One way this could be accomplished is to migrate this library from ESCPOS_NET to ESCPOS_NET.Core, which includes the BasePrinter, FilePrinter, NetworkPrinter and MemoryPrinter, then split out ESCPOS_NET.Serial.Desktop and ESCPOS_NET.Serial.Mobile (or perhaps ESCPOS_NET.Serial.SystemIOPorts and ESCPOS_NET.Serial.SerialPortStream)?  These libraries would just contain the implementation of the serial port library that overrides the base printer.  Another advantage of this would be people not using serial port printers (for example, network printers) would not need to take on an additional dependency to a serial library.  Thoughts?

**Comment by YZahringer** [comment]
`System.IO.Ports` supports Linux, macOS, UWP and Win32: https://github.com/dotnet/corefx/tree/master/src/System.IO.Ports/src/System/IO/Ports

I haven't tested on Android, which natively supports [UART](https://developer.android.com/things/sdk/pio/uart), but to use converters USB<->RS232 through Android, I had to implement FTDI protocol to USB communication.

iOS is not supported because it does not support SerialPort.

I did some tests with `SerialPortStream` on UWP, I couldn't get it to work. Looking at the code, it makes calls to [Win32 DLLs](https://github.com/jcurl/SerialPortStream/blob/v2.x/code/Native/Windows/UnsafeNativeMethods.cs), which is not allowed in a UWP application that is Sandboxed.

From my point of view, it is better to use the implementation of .NET Core, which supports more platforms than `SerialPortStream`, more standard and more maintained.

**Comment by lukevp** [comment]
sixlabors imagesharp is going to remain a dependency for now as it has better memory performance and does not require installation of libgdiplus on unix platforms.  The dependency on serialportstream has been removed in release/1.0.0.   Thanks for the PR, the release/1.0 merge will contain the update to system.io.ports.

**Pull request closed without merging**
