### PR TITLE
Implementing 2D barcodes

### PR DESCRIPTION
**Pull request by igorocampos**
I refactored the DataValidator class, however with no harm to its consumers (the usage remained exactly the same). The base abstract class was created in order to centralize common validation code.

I did not do an extensive validation for the 2D codes, but it's all in place for someone with the proper knowledge.

QRCodes and PDF417 2D Code were implemented, but I've never used nor tested the PDF417, I currently have no ESC/POS printer to adjust whatsoever. My code was 100% based on an ESC POS manual that I have, and I am 95% sure that the QRCode part is accurate, because I'm using similar code in my library.

I created an extension method for an easier list adding, but feel free to modify it or throw away, it's not really necessary for the implementation.

### CODE REVIEW

**Comment by ssoellinger** [comment]
Hi, great work, i test the QrCode seems to work pretty fine on the Epson. You forgot to implement the Interface in ICommandEmitter for the Methode Print2DCode(TwoDimensionCodeType type, string data, Size2DCode size = Size2DCode.NORMAL, 
            CorrectionLevel2DCode correction = CorrectionLevel2DCode.PERCENT_7);

I still have a issue to cover one Printer ( POS80BSU). 
I used those bytes for this Printer : 1b 5a 01 00 05 cc 00 then I could print the QrCode.

**Comment by igorocampos** [comment]
@ssoellinger 
I have pushed the method in the interface. But didn't understand what you meant by 
> I used those bytes for this Printer : 1b 5a 01 00 05 cc 00 then I could print the QrCode.

Is this something I should change somewhere?

**Comment by ssoellinger** [comment]
@igorocampos ; Sorry for the later reply the printer from [Shenzhen HCC Technology Co,](http://www.szhcct.com/index.php?m=content&c=index&a=show&catid=80&id=498) have own implementation of the QrCode which is not ESC Standard, i am not Sure if there Commads is covered with this Pull Request? If possible it would be greater to add them. 
here is the Technical Documanation:
image

[Thermal Printer Technical Manual(V1.02).pdf](https://github.com/lukevp/ESC-POS-.NET/files/4873099/Thermal.Printer.Technical.Manual.V1.02.pdf)

**Comment by lukevp** [comment]
Everything looks good except for the code style, I follow the StyleCop default rules which require braces around all blocks (if, loops, etc.) even if they are single statements.  The main reason for this is if someone is refactoring, they can accidentally make an if statement appear to be 2 lines but not capture the second statement.  It makes it less likely to have future bugs.

For @ssoellinger 's request on the alternate byte sequence, that was the purpose behind the Base emitters and the Epson emitter inheriting from the Base emitter - we can make a separate HCCTG emitter that inherits from Base Emitter and overrides the commands that are not ESC-POS compliant, but the rest of the implementation doesn't have to be copied.  @igorocampos  if you could change the formatting of the blocks I can merge this and then you or @ssoellinger  are welcome to add the HCCTG emitter with the other byte sequence!

**Comment by lukevp** [comment]
I just went ahead and added StyleCop to the project since I've been wanting to do that anyway as it's more mature now, and I went thru and fixed a bunch of formatting inconsistencies that have happened from previous PRs.  You'll have to pull and fix any merge conflicts, shouldn't be too bad though.

**Comment by igorocampos** [comment]
Got it, will try to do so tonight :)

Sorry about the code style, I guess I should've guessed so looking at the code :P 

@ssoellinger I see. Hey, another thing I am interested in: I see in your screenshot specific commands to print Datamatrix 2D code. I looked for it in my EPSON manual, but couldn't find any references to it. Do you know the command sequence to print Datamatrix in an EPSON printer?

**Comment by ssoellinger** [comment]
@igorocampos : As i know the is a specific command for the HCCTG Printer. There should not be a counter part for Epson. Also the Epson Matrix for QrCode does not work on HCCTG Printers. That is the reason, I ask for adding this command.  

@lukevp  good idea with the HCCTG emitter. But would it be better to support both in on emmitter because it is easier than to emitter and i will use either command depending on the printer i am currently using

**Comment by igorocampos** [comment]
Just a note:
I was really mislead by 3d0998fa5b8c534011ad22047d334d2b7a27b047 message... Never would thought that a style cop commit would change a method's signature and behavior. I was wondering for a while why the merge conflict was so messy if this was only about the code style.

Fixing new validator behavior conflict now.

**Comment by igorocampos** [comment]
Another thing that I would disagree, but it's already on master and I am not changing is:
https://github.com/lukevp/ESC-POS-.NET/blob/ca3b3027d4642caea4deb53b21340593705ad783/ESCPOS_NET/Emitters/BaseCommandEmitter/BarcodeCommands.cs#L13

IMHO, `BarcodeCode code` should actually be a nullable `BarcodeCode? code` and have `code = null` whenever a barcode that was not CODE128 was sent to be printed, or at least add a new enum value for `None`. Otherwise are getting barcodes that don't have a code type with Code B.

**Comment by igorocampos** [comment]
@lukevp I fixed all merge conflicts, let me know if you need anything else

**Comment by lukevp** [comment]
@igorocampos  you're right on the commit, I mistakenly committed a refactor of a previous merge that added CODE128 CODEC support along with the stylecop commit.  I'm sorry for the confusion.  I do also agree with the nullable code change.

**Comment by lukevp** [comment]
@igorocampos PR Merged.  Thank you so much for adding this feature!  Do you have any sample code that you could add to the ConsoleTest app?

**Comment by igorocampos** [comment]
@lukevp, you're welcome.  I can add some, yes. Any kind of qrcode in particular, and any sample data to be contained on the qrcode e.g. website?

**Comment by lukevp** [comment]
You could link it back to this repo, https://github.com/lukevp/ESC-POS-.NET/
Is that too much detail to have an easily-printable QR code?

**Comment by igorocampos** [comment]
don't think so. I'll come up with the PR for that (prob. tonight or tomorrow)

**Comment by ssoellinger** [comment]
@igorocampos  you did not include  HCCTG emitter or?.

**Comment by igorocampos** [comment]
@ssoellinger  I did not, sorry :(

**Comment by igorocampos** [comment]
@lukevp done in #62

**Pull request merged**
