### PR TITLE
Master

### PR DESCRIPTION
**Pull request by paul-turner-github**
Cleaned up the Dispose methods to implement the pattern correctly.  Updated the write process to ensure that connections are open and can be written too.  Included a delegate event to pass in EventArgs to help with monitoring.

### CODE REVIEW

**Comment by lukevp** [comment]
Hey @paul-turner-github thank you so much for the PR! We are currently reviewing #37 which will also be merged into master once release/1.0 is stabilized. I don’t suppose you would be willing to help test that PR so we can get it all merged down and then we can update your PR and see where there may be conflicts?

Thanks again!

**Comment by paul-turner-github** [comment]
Yep happy to help. I will be adding some functions for ZPL (Zebra Printers) and also a local polling service to get print jobs from REST services.

**Comment by lukevp** [comment]
@paul-turner-github release/1.0 has been merged, can you please rebase your changes on top of the latest master and fix the merge conflicts?

**Comment by lukevp** [comment]
@paul-turner-github bump, please let me know if you're still interested in working on this PR.

**Comment by lukevp** [comment]
No comment from user who opened PR since 1/21. Closing PR.  Reviewed changes and not relevant on new branch due to significant refactoring but would appreciate any contribution to cleanup that you'd like to do in the future.

**Pull request closed without merging**
